const dicionario = {
    "Absolute A-Force": {
        "Liberty": "1 – The strategy is very simple. All opponents have Taunt, so you can choose who you attack. Avoid attacking Ms. Marvel (Classic) until you eliminate the other opponents. The exception is Falcon Joaquin (Special), which you should use on Kahhori, so if Ms. Marvel (Classic) is next to her then it is inevitable that you hit her. Captain (Sam) Ultimate also hits all opponents, so you can make an exception here as well because it will fill your entire team’s Speed Bar.",
        "Absolute A-Force": "2 – One of the best counters for Absolute A-Force is Absolute A-Force. Your Kahhori passively, on Spawn, attacks the opponent Kahhori first, applies Exposed to her and prevents her from playing twice at the start. So the opponent Kahhori will only be able to use Special in her third turn. Focus on Ms. Marvel (Classic) until she loses Taunt. With Kahhori – twice Basic, then in her second turn – Special, with Ms. Marvel (Classic) – Ultimate. When the opponent Ms. Marvel (Classic) loses Taunt, switch your focus to the rest of the opponents. Kahhori’s and Medusa’s Ultimate can deal massive damage and eliminate most of the opposing team. After that, it’s all about bringing the fight to the end. Leave Ms. Marvel (Classic) for last.",
        "Gamma + Mephisto (no She-Hulk)": "3 – With Mephisto, play Empowered Basic on Ms. Marvel (Classic), and with Red Hulk use Special on her. You can use Special with Mephisto on his second turn. When Kahhori plays her Special, Red Hulk will get 5 Charged and will be able to use Ultimate, thus applying his Battlefield Effect to the opponent’s side. Opponents will have all negativities from Mephisto losing Empowered and Red Hulk Ultimate, but most importantly Heal Block, Trauma, and Bleed. After Mephisto plays his Ultimate – you’ll eliminate them without a problem. When Ms. Marvel (Classic) loses Taunt, focus on Kahhori. The Deathproofs you get from Mephisto’s Battlefield Effect and the Brawn’s Passive (as well as Deflects on Spawn) are essential for your team to withstand attacks. If Mephisto and Red Hulk are maxed, massive punch-ups are possible.",
        "Knowhere + Odin + Apocalypse (no Star-Lord (Annihilation) and Thor (Infinity War))": "4 – Nova is a fast enough character to play after Kahhori and allows Odin to Assist him. After that happens, with Odin, when it’s his turn to play, play Special (if you’re not Ability Block). When you apply the Battlefield Effect on the enemy side, everything will become much easier. Huge punch ups are possible if Odin is Maxed – Especially if he is GT20 (but it doesn’t need to be). Apocalypse is there to passively increase Odin’s Health and Accuracy. And if he manages to play, to use Ultimate and Empowered Basic on Ms. Marvel (Classic). If he doesn’t make it, if he is killed before his turn to play, the fight may be delayed, but you eventually win.",
        "Gamma + Apocalypse + Morgan Le Fay (no She-Hulk and Abomination)": "5 – If your Morgan Le Fay and Red Hulk are solidly upgraded (at least level 100 and GT19), you can destroy the opposing Absolute A-Force team with this combination. A solid punch-up is possible (assuming Apocalypse is maxed), but do not try more than 25%. Red Hulk should be Raider, MLF Skirmisher, and Apoc Striker. MLF should be positioned next to Red Hulk. With Red Hulk, play Special on Ms. Marvel (Classic) which will fill Apocalypsi’s Speed ​​Bar and enable him to play his Ultimate and Empowered Basic, thus eliminating Ms. Marvel (Classic). MLF will also get a Speed ​​Bar, so she will play before Kahhori and we use Ultimate with her, which will apply Ability Block to Kahhori. So Kahhori won’t be able to use Special and cause us huge problems. Soon after Red Hulk will build up enough Charged to use his Ultimate and when we do, victory is upon us. Eliminate Kahhori first, then Medusa.",
        "Cabal + Mephisto + Ares": "6 – Cabal, Mephisto, and Ares can get Absolute A-Force if it’s a weaker team than yours. Around 1.5 million punch downs is a good limit. With Mephisto, play Empowered Basic on Ms. Marvel (Classic), and focus on her from the start. When you eliminate her, focus on Kahhori.",
        "Astral": "7 – In case the opponent has a slightly weaker AAF team, Astral can successfully deal with them. Especially if the Overpower rating on your characters is higher than the opponent’s. Astral has strong mitigation and sustain, and they will withstand the opponent’s starting onslaught without problems. When it’s their turn to play, they will destroy AAF. No special tactics are necessary, but it needs to be a solid punch down – around 2 million."
    },
    "Abosolute A-Force + Professor Xavier + Knull": {
        "Liberty + Quasar (no War Machine)": "1 – Joaquin – Skirmisher, Quasar – Striker. Use Falcon (Joaquin)’s Special on Professor, and then use Quasar’s Ultimate on Professor. That should kill Professor Xavier. After that it’s easy."
    },
    "Absolute A-Force + Super Skrull": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – With Mephisto use Empowered Basic on Ms. Marvel (Classic). With Knull, Red Goblin and Void Knight use Ultimates. Those 3 attacks should be enough to put at least one of the opponents in red HP, and you will get enough Speed ​​Bar to continue destroying opponents. Focus on Ms. Marvel (Classic) and Kahhori.",
        "Absolute A-Force": "2 – We are forced to attack Ms. Marvel (Classic) at the start, so don’t save Abilities, use them all, and your primary target is Ms. Marvel (Classic) until she loses Taunt. When that happens, use Ultimate with Kahhori, but attack the other opponents (do not touch Ms. Marvel), then do the same with Medusa. It will certainly eliminate some of the opponents if your Kahhori and Medusa are strong enough. Focus on opponent Kahhori, then Medusa and Skrull, leave Ms. Marvel (Classic) for the end.",
        "Cabal + Mephisto + Ultimus": "3 – With Ultimus (he sould be Raider), use Special on the first turn, then Ultimate (you need to target Ms. Marvel (Classic) because she has Taunt). With Mephisto, Empowered Basic on Ms. Marvel (Classic). With Cabal characters, use all Abilities if you can (do not save anything). Focus on Ms. Marvel (Classic) first, then on Kahhori.",
        "Liberty": "4 – Use the Falcon (Joaquin) Special on the Skrull and with Peggy Stun Kahhori. Focus on Kahhori and Skrull, then Medusa.",
        "Absolute A-Force + Black Knight + Super Skrull": "5 – We use this counter if we don’t have Wasp and Ironheart built high enough. Otherwise, the full Absolute A-Force team can get the job done. At the beginning of the fight, we attack Ms. Marvel (Classic), with Kahhori, then with Skrull (Basic or Special), and then with Black Knight (Special). This will provide Black Knight with Charged and he will be able to counter the opponent’s attacks. After that, focus on Ms. Marvel (Classic) and the rest of the opponents. When using any Ability that attacks multiple enemies (BK Ult, Kahhori Ult, Medusa Ult) try to hit as many enemies as possible, but avoid hitting Ms. Marvel (Classic) if she has Charged."
    },
    "Absolute A-Force + Super Skrull + Dormammu": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – With Mephisto use Empowered Basic on Ms. Marvel (Classic). With Knull, Red Goblin and Void Knight use Ultimates. Those 3 attacks should be enough to put at least one of the opponents in red HP, and you will get enough Speed ​​Bar to continue destroying opponents. Focus on Ms. Marvel (Classic) and Kahhori. Mephisto will stop Revives.",
        "Liberty": "2 – Use the Falcon (Joaquin) Special on the Skrull and with Peggy Stun Kahhori. Focus on Kahhori and Skrull, then Medusa.",
        "Cabal + Mephisto + Ultimus": "3 – With Ultimus (he should be Raider), use Special on the first turn, then Ultimate (you need to target Ms. Marvel (Classic) because she has Taunt). With Mephisto, Empowered Basic on Ms. Marvel (Classic). With Cabal characters, use all Abilities if you can (do not save anything). Focus on Ms. Marvel (Classic) first, then on Kahhori. Mephisto will prevent Revives.",
        "Absolute A-Force": "4 – We are forced to attack Ms. Marvel (Classic) at the start, so don’t save Abilities, use them all, and your primary target is Ms. Marvel (Classic) until she loses Taunt. When that happens, use Ultimate with Kahhori, but attack the other opponents (do not touch Ms. Marvel), then do the same with Medusa. It will certainly eliminate some of the opponents if your Kahhori and Medusa are strong enough. Focus on opponent Kahhori, then Medusa and Skrull, leave Ms. Marvel (Classic) for the end. Medusa can permanently kill opponents with her attacks, and it will neutralize Dormammu’s Revive. Also, any opponent you apply Exposed on with Kahhori will not be able to Revive.",
        "Absolute A-Force + Black Knight + Super Skrull": "5 – We use this counter if we don’t have Wasp and Ironheart built high enough. Otherwise, the full Absolute A-Force team can get the job done. At the beginning of the fight, we attack Ms. Marvel (Classic), with Kahhori, then with Skrull (Basic or Special), and then with Black Knight (Special). This will provide Black Knight with Charged and he will be able to counter the opponent’s attacks. After that, focus on Ms. Marvel (Classic) and the rest of the opponents. When using any multiple enemies hit Ability (BK Ult, Kahhori Ult, Medusa Ult) try to hit as many enemies as possible, but avoid hitting Ms. Marvel (Classic) if she has Charged. Medusa can permanently kill opponents with her attacks, and it will neutralize Dormammu’s Revive. Also, any opponent you apply Exposed on with Kahhori will not be able to Revive. Also, any opponent Black Knight kills with his counters or Special or Ultimate is permanently dead."
    },
    "Absolute A-Force + Odin": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – Mephisto – Empowered Basic on Ms. Marvel (Classic), and on his second turn Basic on the same target. With Void Knight use Ultimate, with Knull – also Ultimate. With Carnage Special, and with Red Goblin Ultimate. Even before we do all these attacks, we will lower at least one of the opponents to red HP, so we will get a bunch of Speed ​​Bar and play constantly until we eliminate them all.",
        "Liberty + Mephisto (no War Machine)": "2 – Use Mephisto’s Empowered Basic on Odin, then hit him with a Basic attack. Target Kahhori with Falcon’s (Joaquin) Special. Use the Special with Peggy and also target Kahhori."
    },
    "Absolute A-Force + Mephisto + Super Skrull": {
        "Liberty + Knull": "2 – With Falcon (Joaquin) use the Special on the Skrull. With Peggy Carter – Special on Kahhori. With Knull – Special on Kahhori. With Captain (Sam) use Ultimate, and with Patriot – Special. After Kahhori, focus on Mephisto then Skrull then Medusa. Leave Ms. Marvel (Classic) for the end.",
        "Liberty + Mephisto": "3 – At the start, we focus on Kahhori. Mephisto Empowered Basic plus Basic, Peggy Special, Falcon (Joaquin) Special. Everything on Kahhori until we kill her. In the second Peggy turn, it is important to target Mephisto and use the Ultimate (to apply Ability Block on him and prevent him from using his Ultimate). After eliminating Kahhori, we focus on Mephisto, Skrull, and Medusa. We leave Ms. Marvel (Classic) for the end."
    },
    "Absolute A-Force + Odin + Super Skrull": {
        "Liberty + Mephisto (no War Machine)": "1 – Use Mephisto’s Empowered Basic on Odin, then hit him with a Basic attack. Target Skrull with Falcon’s (Joaquin) Special.",
        "Mephisto + Ares + Ultimus + Apocalypse + Scarlet Witch (Zombie)": "2 – Use Mephisto’s Empowered Basic on Ms. Marvel (Classic), then finish her with Ultimus Ultimate. After the kill, Ultimus through his Passive, fills Speed Bar by 15% to all his allies, and your Apocalypse will play before enemy Odin. Kill Odin with Apocalypse Ultimate + Empowered Basic.",
        "Liberty": "3– Use Facon’s (Joaquin) Special targeting Super Skrull, then full focus on Odin, but do not have him as the primary target when using Peggy’s Special (Odin should be one of the adjacent targets).",
        "Cabal + Apocalypse + Ultimus": "4 – With Ultimus, play Basic on his first and second turns targeting Ms. Marvel (Classic). On his third turn, go for the kill – use the Ultimate. After that, focus on Odin.",
        "Quasar + Phoenix Force + Scientist Supreme + Nimrod": "5 – Use Ultimate with Scientist Supreme and Special with Nimrod. Ultimate with Quasar will take off the Taunt from Ms. Marvel (Classic). Then with Omega Red (Phoenix Force) use Special – target Odin. After that, finish off Odin, then switch your focus to Kahhori and Medusa. Leave the Skrull and Ms. Marvel for the end."
    },
    "Kahhori + Ms. Marvel (Classic) + Knull + Mephisto + Super Skrull": {
        "Liberty + Knull + Ultimus": "2 – Start by using Ultimus’s Ultimate on opposing Knull, he will apply Ability Block on Mephisto. Focus on Mephisto. With Joaquin use Special on enemy Skrull. With Peggy use Special on Kahhori. With Knull and Sam use Ultimates. Enemy Knull and Mephisto should be dead. After that avoid targeting Ms. Marvel (Classic) if she has Counters or Charges. Focus on controlling Kahhori and killing Skrull, and try to do as much damage as you can on Ms. Marvel (Classic) while she is out of Charge/Counters."
    },
    "Kahhori + Ms. Marvel (Classic) + Medusa/Super Skrull + Mephisto + Thanos (Endgame)": {
        "Liberty + Knull (no War Machine)": "1 – With Falcon (Joaquin) we use Special on Skrull, and if there is Medusa instead of Skrull, then on Kahhori. With Peggy Special on Kahhori, with Cap (Sam) use Ultimate, and with Patriot Special. Focus on the opponent’s side opposite from where Ms. Marvel (Classic) stands. Try not to hit her. With Knull, use the Special on the first turn. Mephisto must be eliminated before he can use his Ultimate. Don’t be afraid to drop Thanos (Endgame) below 50% HP. Leave Ms. Marvel (Classic) for the end.",
        "Absolute A-Force + Mephisto + Knull (no Ironheart and Wasp)": "2 – We focus on Ms. Marvel (Classic) from the very start until we eliminate her. 2 Basic attacks with Kahhori, Empowered Basic and Basic with Mephisto, Ultimate with Knull, and Special with Medusa. Opposing Mephisto, can’t be in his Empowered state at the beginning of combat, which makes the fight much easier. After we eliminate Ms. Marvel (Classic) we focus on the rest of the enemies. An easy fight, for which we still need a very strong team."
    },
    "Kahhori + Ms. Marvel (Classic) + Spider-Man (Pavitr) + Red Goblin + Carnage": {
        "Mighty Avengers": "1 – Use Hercules’ Special on Ms. Marvel (Classic) to remove all her buffs and, most importantly, all her Charges. After that, focus your attacks on Kahhori until your Invisible Woman gets a turn. When she does, use her Ultimate on Ms. Marvel (Classic) to Stun her, allowing you to defeat her without worrying about her countering and gaining more Charges. Once Ms. Marvel (Classic) is eliminated, the battle is essentially won. Your next main target should be Kahhori, and that’s it.",
        "Undying + Mephisto": "2 – Use Mephisto’s Empowered Basic and standard Basic attacks on Ms. Marvel (Classic). If she survives, continue to focus on her until she is defeated. Once she is down, shift your attention to Kahhori for an easy victory.",
        "Absolute A-Force": "3 -Focus entirely on Ms. Marvel (Classic) until she loses her Taunt, then shift your attention to Kahhori. Other opponents will be eliminated by your area-of-effect attacks. Don’t hesitate to use any of your abilities. Once Kahhori is defeated, finish off Ms. Marvel (Classic)."
    },
    "Kahhori + Ms. Marvel (Classic) + Odin + Knull + Dormammu": {
        "Liberty + Mephisto (no War Machine)": "1 – Start by using Maphisto’s Basic attack on Odin, followed by Mephisto’s Special attack on Odin. Then, Falcon (Joaquin), uses his Special target the enemy character next to Odin. Next, Peggy should use her special attack on Kahhori. Use Cap (Sam)’s Ultimate, and have Patriot use his Special. Save Ms. Marvel (Classic) for the end.",
        "Cabal + Ultimus + Odin": "2 – At the start of the fight, focus on Ms. Marvel (Classic) since she has Taunt. With Ultimus, begin by using the Special move, followed by the Ultimate. For each subsequent attack with Ultimus, use the Basic move. For Cabal characters, follow this sequence: Iron Patriot – Special, Namor – Ultimate, and The Leader – Special. These attacks, along with various assists from Cabal characters and continuous assists from our Odin, will be enough to eliminate Ms. Marvel (Classic) twice (because of Dormammu, she has Revive). Once she is defeated, immediately shift your focus to the opponent’s Odin. You’ll be able to eliminate him before it’s his turn to play. Use the Special with your Odin. After that, it will be 5 vs 2. Control Kahhori and eliminate Knull and her."
    },
    "Alpha Flight": {
        "Mercs For Money": "1 – Hard Counter – With OML use Special on the first turn and Ultimate on the second turn. With other characters, use all available Abilities.",
        "Mighty Avenger": "2 – Hard Counter – use all available Abilities.",
        "Liberty": "3 – Hard Counter – use all available Abilities. Use Special with Joaquin on Northstar, and with Peggy, use Special on the same enemy.",
        "Illuminati with Captain Britain": "4 – Focus on Sasquatch until it loses Taunt, then switch your focus to Northstar and Guardian. Use all available Abilities.",
        "4 Out Of Time (no Black Knight)": "5 – Four OOT characters without Black Knight can withstand Alpha Flight’s initial attacks and get them later. Focus on Sasquatch until it loses Taunt, then switch focus to Northstar and Guardian. Use all available Abilities.",
        "Knowhere + Apocalypse (no Star-Lord Annihilation or Thor Infinity War)": "6 – At the start of combat, we have to attack the Sasquatch because he has Taunt. With Nova, use the Special, and then you have to withstand the opponent’s attacks until Apocalypse’s turn to play. If he has an Overpower level higher than Alpha Flight opponents, he can win this fight by himself. With him, use Ultimate and Empowered Basic and thus eliminate Sasquatch and do huge damage to the others. With Cosmo, use the Special to remove Buffs from the remaining opponents, then finish the fight.",
        "Gamma + Apocalypse (no Abomination)": "7 – Red Hulk plays first, we use Special with him and thus fill the Speed ​​Bar of Apocalypse, which allows him to play earlier. With Brawn, we use Ultimate – because if we use Special and copy a bunch of buffs from the opponents, Northstar will flip it all shortly after. With Apocalypse – Ultimate + Empowered Basic on Northstar (because Sasquatch will almost certainly lose Taunt at that point). After that, we bring the fight to an end by eliminating the Guardian as soon as possible, and then the rest of the Alpha Flight team.",
        "Vigilante": "8 – Use the Ultimate with Silver Sable. Then, with Hit-Monkey, use the Ultimate on Northstar. After that, focus on taking out Northstar."
    },
    "Alpha Flight + Odin": {
        "Liberty": "1 – Focus entirely on Odin from the beginning. Use Joaquin’s Special, Peggy’s Special, Patriot’s Special, Cap Sam’s Ultimate, and War Machine’s Special if necessary. Odin will be defeated, and then you can take care of the rest.",
        "Thunderbolts": "2 – If Taskmaster and Ghost have 3 Diamonds, the approach becomes straightforward. Begin by deploying Taskmaster’s and Songbird’s Ultimates. Follow this with Hyperion’s special attack on Sasquatch. Finally, unleash the ultimate abilities of both Victoria and Ghost on Odin, ensuring they are utilized as Strikers for maximum impact."
    },
    "Alpha Flight + Mephisto + Ares": {
        "Nightstalker + Odin (no Moonknight)": " – focus on Northstar"
    },
    "Annihilator + Mephisto": {
        "Starjammer + Odin (no Havok)": " – always use Odin’s Special in first and Basic in second turn"
    },
    "Annihilator + Odin + Professor Xavier": {
        "Quasar + Ares + Mephisto + Phoenix Force (Quasar needs to have his Awakened Ultimate)": "1 – With Quasar, use his Ultimate but be careful not to hit Odin; instead, try to hit Professor X. Professor doesn’t need to be the primary target, but Odin should not be hit by Quasar Ultimate at all. When Odin uses his Special, he won’t be able to apply the Battlefield Effect because Quasar will have already applied his. With Mephisto, use the Empowered Basic attack on Odin. For Phoenix, make sure to use her Special, and for Ares, also use his Special, targeting Professor X. Once you eliminate Professor X, your primary target will be Odin unless he is defeated before you eliminate Professor. Be cautious not to take Thanos (Endgame) below 50% before Phoenix dies and can use her Dark Phoenix Special. Alternatively, you can defeat Thanos with Quasar’s Special. Avoid using Ultimates until Professor X is defeated. When Dark Phoenix drops Thanos’s (Endgame) health below 50% with her Special, it won’t trigger his Passive.",
        "Quasar + Ares + Odin + Havok + Storm (Quasar needs to have his Awakened Ultimate)": "2 – At the start with Storm, use her Special on Gorr. For Quasar, use his Ultimate, ensuring you target all three Annihilators if possible. If not, it’s acceptable to hit Professor X but avoid hitting Odin. When using Havok, target Professor X with his Special. Havok should be set as a Skirmisher to significantly reduce the chances of Professor X resisting Stun. For Odin, use a Basic attack. Shortly after, the opposing Professor X will be defeated by Odin’s passive damage, so focus on the opposing Odin. Even if you don’t eliminate him before he plays, you should still win, as the opponent’s Odin cannot apply his Battlefield Effect. Be aware of the passive damage from Thanos (Endgame), but you should be able to survive. If Storm survives to use her Ultimate, that’s an added advantage."
    },
    "3 New Annihilator + Odin + Ares": {
        "3 New Absolute A-Force + Apocalypse + Red Hulk": "1 – With Kahhori, use the Basic on Gladiator to remove his Taunt, then use the Basic on Ares to remove his Immunity. Use Medusa’s Special and Ms. Marvel’s (Classic) Ultimate to attack Odin. With Kahhori, use the Special, and with Red Hulk, also use the Special – but target a different character since you cannot rewind Odin’s Speed Bar. With Apocalypse, use the Ultimate, followed by the Empowered Basic on Thanos (Endgame) to avoid taking passive damage from him.",
        "Liberty": "2 – With Falcon (Joaquin), use Special on Gorr to reduce his Speed Bar. This will allow Odin to act before all the other opponents. Odin will use his Special, but won’t apply the Battlefield Effect since he hasn’t had a chance to assist before his first move. With Peggy, use her Special on Ares, and then focus on Odin as your primary target. All other characters should also concentrate on Odin. Use Captain Sam’s Ultimate, Patriot’s Special, and War Machine’s Special to deal damage. If your three new Liberty characters are GT20 (specifically if their Overpower rating is higher than the opponent’s), you should have enough damage to eliminate Odin before his turn. If you don’t have an advantage in Overpower, this counter-strategy is not recommended (but still can work). Once Odin is eliminated, the rest of the battle will become much easier.",
        "Liberty + Mephisto (no War Machine)": "3 – With Mephisto: Empowered Basic and Basic on Odin, with Falcon (Joaquin): Special on Gorr, with Peggy: Special on enemy next to Odin. After Patriot Special and Captain Sam Ultimate Odin should be eliminated. After that finish the rest. Focus on Gorr first, and try to leave Thanos (Endgame) for the end.",
        "Nightstalker + Mephisto (no Moon Knight)": "4 – This counter works best if your Blade and Oath have a higher Overpower ranking compared to the opponent’s Gladiator and Odin. Start by using Mephisto’s Empowered Basic attack along with his standard Basic attack on Gladiator. With Blade, use his Ultimate ability on Ares (especially if Ares is positioned next to Gladiator – that’s an ideal scenario). Once you’ve taken down the two opposing protectors, shift your full focus to Odin. If you have the Overpower advantage, you should be able to defeat him before he gets a chance to act. However, we don’t recommend using this counter if you lack the Overpower advantage mentioned above.",
        "Orchis + Mephisto (no Omega Sentinel": "5 – This is an ideal counter to use if your Orchis characters have a higher Overpower rating compared to the opponent’s Odin and Gladiator. Start by using Mephisto’s Empowered Basic followed by a Basic on Gladiator. With Scientist Supreme, activate her Ultimate. Use Nimrod’s Special ability to target all enemies, and then use Lady Deathstrike’s Special or Basic ability to attack the remaining opponent with Taunt (either Gladiator or Ares). When using Sentinel, activate his Ultimate on Odin and have his minions focus their attacks on Odin as well. This should be enough to eliminate Odin. Afterward, concentrate on defeating the remaining opponents. However, we do not recommend using this counter strategy if your Orchis team does not have an Overpower advantage over Gladiator and Odin.",
        "Undying + Odin": "6 – Use Hela’s Minion (Greg) to attack Gladiator or Ares with his Special. This will reduce the Speed Bar of all opponents except Odin, allowing the enemy Odin to take the first turn. The enemy Odin will use his Special, but he won’t apply his Battlefield Effect because he didn’t assist. Next, use your Odin’s Special. Since your Odin already assisted when Greg attacked, your Odin will successfully apply the Battlefield Effect to the enemy side. This gives you a strong advantage that will be difficult for the opponent to overcome. Thanos (Endgame) can deal significant passive damage when we reduce him below 50% HP, but he won’t be able to eliminate your team. The enemy Odin will eventually use his Ultimate, causing serious damage, but he still won’t apply the Battlefield Effect to your side because he used his Ultimate instead of his Basic attack. With the rest of your team, focus all attacks on the opposing Odin. Once you take him out, you should have no trouble securing victory."
    },
    "Annihilator + Knull": {
        "Hive-Mind + Knull (no Venom)": "1 – Start with Void Knight’s Ultimate, then use Carnage’s Special. You need to target the Gladiator because he has the Taunt. With Knull, use his Special first, as it will summon an extra Carnage and give you a significant Speed Bar boost when you bring any opponent’s health down to the red zone. Knull’s next move should be his Ultimate ability. By this point, some enemies should be defeated, and others should have low health. Be cautious of Thanos (Endgame) and his passive damage, as it can create a challenging situation. However, as long as at least one Carnage, Knull, and one other character are still alive, you should be able to win this easily. If your Hive-Mind characters are weak, consider swapping out Gwen for Odin. With Odin on your team, victory becomes much simpler.",
        "Mercs For Money + Ares (no Deathpool)": "2 – Ares is mainly there for his passive abilities. After Ultimus and Gorr take their turns, Ares will most likely be defeated. The key point for you is to ensure that Old Man Logan (OML) gets his turn. Ares will strip all buffs from the enemy team, allowing you to Stun Thanos (Endgame) with OML right at the start of the battle. Focus on taking down Knull as your priority. Use Pandapool’s Ultimate and Daken’s Special, combined with OML’s assist and the damage from his Special, to eliminate Knull quickly. With Deadpool you can Stun Gladiator and after that focus on Gorr and Thanos (Endgame). When Thanos (Endgame) deals passive damage, it’s crucial that both Daken and Old Man Logan have Revive available to sustain the fight.",
        "Super Skrull + Odin + Doctor Doom + Phoenix Force Duo": "3 – This is an easy fight for this team. Start with Skrull by using his Special, followed by his Basic attack. For Odin, use his Special. When Gladiator loses Taunt, shift your focus to Knull. While Phoenix Force and Doom aren’t crucial, it’s still helpful to have them on your team (though Doom might end up dying from friendly fire). Make sure to include one additional Hero and two Villain characters alongside Skrull and Odin.",
        "Thunderbolt": "4 – Songbird’s Ultimate, Taskmaster’s Ultimate, and Hyperion’s Special should be used on Gladiator. Additionally, Victoria Hand’s Ultimate should be used on Knull or any character adjacent to him."
    },
    "Gorr + Gladiator + Thanos (Endgame) + Odin + Moondragon": {
        "Liberty + Mephisto (no War Machine)": "1 – With Mephisto – Empowered Basic + standard Basic on Odin. With Falcon (Joaquin) – Special on character next to Odin. Odin should be dead, if not – finish him off. After he dies, feel free to drop Thanos (Endgame) below 50% HP to trigger his Passive, and then finish off the opponents.",
        "Absolute A-Force": "2 – With Kahhori use Basic on Gladiator, then Basic on Odin, then Special on Odin. After that focus on Odin: Medusa Special, Ms. Marvel (Classic) Ultimate, and Ironheart Special on target next to Odin if he has really low HP, or Basic directly on Odin if he has a bit more HP – he should be down. With Wasp, you can Stun Gladiator (Special). After that trigger Thanos (Endgame) Passive, and finish the enemies.",
        "Nightstalker + Mephisto (no Moon Knight": "3 – With Mephisto use Empowered Basic and Basic on Gladiator. With Blade use Ultimate on Gladiator. If your Mephisto and Blade are huge (especially if Blade is GT20 and opponent Gladiator is not GT20), he should be dead. Then switch your focus to Odin. With Oath using Ultimate on Odin, and with assistance from Blade it can kill him if he is GT19 and Blade + Oath are GT20 (and they should be because they are great for Xavier Saga). After Odin is down, finish the rest. So, basically, this counter can work without problems if your Blade and Oath are GT20 and opponent Odin and Gladiator are not.",
        "Orchis + Mephisto (no Omega Sentinel)": "4 – Here’s the sequence: Mephisto – Use Empowered Basic and then Basic on Gladiator. Scientist Supreme – Use her Ultimate. Nimrod – Use his Special. Lady Deathstrike – Special or Basic on Gladiator, depending if the enemy next to him is dead or alive. If there is no one next to him, use Basic. Gladiator should be defeated after this. Then, focus all attacks on Odin until he is down. He would have around half of HP, and you can finish him with Sentinel Ultimate and Minions. Once Odin is defeated, finish off the remaining enemies."
    },
    "Astral": {
        "Undying + Phoenix Force Duo (without Scarlet Witch (Zombie))": "1 – With Iron Man (Zombie), use Special on Emma Frost (X-Men), and with Hela Ultimate on Emma Frost (X-Men). You will spread every negativity from her to the rest of the Astral team – most importantly Ability Block. With Omega Red (Phoenix Force), use a Special on the far left or far right opponent. With Juggernaut (Zombie), use the Ultimate to hit three opponents standing next to each other.",
        "Cabal + Kang + Apocalypse": "2 – Ideal Iso-8: Kang – Striker, Apocalypse – Striker, Namor – Raider, The Leader – Skirmisher, Iron Patriot – Striker. With Kang, use a special so that one of the three targets he hits is Shadow King, but if Kang is Striker Emma Frost (X-Men) can’t be your primary target. With Apocalypse Use Ultimate targeting Emma Frost (X-Men). He will Stun her with an Iso-8 attack. Use Empowered Basic on the Shadow King and eliminate him from the fight. After that don’t let other opponents play, reduce their Speed Bar with Namor Ultimate. Focus on the Ancient One and Doctor Strange."
    },
    "Astral + Cosmic Ghost Rider": {
        "Vigilante": "1 – With Silver Sable, use Ultimate. That will put Ability Block on Strange and Emma (X-Men), so with Hit Monkey, we can use Ultimate on Ancient One to Stun her. With Daredevil (Modern), we use Special on Strange, and with Punisher Ultimate on Shadow King (if Punisher does not have Ability Block). Eliminate Strange first, then Shadow King and the rest of the opponents.",
        "Absolute A-Force": "2 – Don’t save anything of Abilities. Focus on Doctor Strange first, then Shadow King. Cosmic Ghost Rider will die from AOE damage. Finish Emma and Ancient at the end.",
        "Mercs for Money + Apocalypse": "3 – Use Panda’s Ultimate and target Shadow King. With OML, use the Special to target Strange. You might not succeed in Stunning him, but that’s okay. With Apocalypse, use both the Ultimate and Empowered Basic abilities to target Shadow King. With assistance from OML, Shadow King should be eliminated. Then, focus on Strange using OML’s Ultimate and Daken’s Special. Once Strange is defeated, finish off the remaining enemies.",
        "Liberty": "4 – Focus on Strange from the beginning. Do not hesitate to use any Abilities. Once Strange is eliminated, switch your focus to Shadow King. If you have some of the Liberty characters at Overpower Rank 11 (at least Peggy) and the opposing Astral team does not, then this will be a very easy fight for you.",
        "Mephisto + Nightstalker / Orchis": "5 – With Mephisto, use Empowered Basic plus standard Basic on Shadow King, then continue focusing on him with other characters. Once he is eliminated, switch your focus to Ancient One and Emma Frost (X-Men). Leave Strange for the end because he can’t revive anyone while Mephisto is present. Cosmic Ghost Rider will die from AOE damage."
    },
    "Astral + Odin": {
        "Quasar + Ares + Storm + Jean Grey + Havok": " (Quasar must have Awakened Ultimate)"
    },
    "Astral + Blue Marvel": {
        "Brimstone + Guardian (no Elsa Bloodstone)": " (your Daimon Hellstrom needs to have 1+ Daimonds)"
    },
    "Brimstone": {
        "Brimstone + Emma Frost (no Elsa Bloodstone)": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Winter Guard": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Fantastic Four (MCU) + Emma Frost": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Emma Frost + Emma Frost (X-Men) + Storm + Jean Grey + Ares": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Emma Frost + Black Cat + Scarlet Witch (Zombie) + Havok + Songbird": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Emma Frost + Emma Frost (X-Men) + Havok + Storm + Black Cat": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective."
    },
    "Brimstone + Apocalypse": {
        "Vigilante": "- Burn attack with Phoenix (Daimon and Hellcat will use their Ultimates) and then: Those counters won’t work if enemy Daimon Hellstrom and Hellcat have Diamonds. However, with those two characters at lower-star, all of these counters should work without much trouble."
    },
    "Fantastic Four (MCU) + Professor Xavier": {
        "Brimstone + Black Cat": "1 – With Hellcat Stun Invisible Woman (Ultimate), and with Black Cat Stun Professor Xavier (Special)."
    },
    "Fantastic Four (MCU) + Professor Xavier + Nightcrawler": {
        "Quasar + Mephisto + Ares + Storm + Black Cat": "1 – With Black Cat use Special on Franklin Richards, with Storm use Special on Invisible Woman (MCU), with Quasar use Ultimate on Professor Xavier.",
        "Quasar + Black Panther (Shuri) + Ares + Storm + Songbird": "2 – Use Black Panther (Shuri)’s Special on Franklin. Use Songbird’s Ultimate. With Storm, use her Special on Invisible Woman (MCU). For Quasar, use the Special on Professor Xavier if he has more than 40% HP—if he has less, use the Ultimate instead. With Ares, use Ultimate on Mr. Fantastic (MCU)."
    },
    "Fantastic Four (MCU) + Professor Xavier + Blue Marvel": {
        "Professor Xavier + Quasar + Yo-Yo + Black Widow + Guardian": " (Yo-Yo – Special on Professor, Black Widow – Basic on Professor)"
    },
    "Fantastic Four (MCU) + Professor Xavier + Odin": {
        "Quasar + Ares + Black Cat + Songbird + Havok or Mephisto if punch up is huge": "1 – Use Songbird’s Ultimate, use Black Cat’s Special to stun Franklin. With Quasar, use the Ultimate ability and aim at Professor Xavier. Once Xavier and Franklin are eliminated, shift your focus to Odin.",
        "Fantastic Four (MCU) + Professor Xavier + Black Cat": "2 – To ensure success in this scenario, assign Skirmisher to Franklin and Striker to Invisible Woman (MCU). Your IW should ideally have 1-3 diamonds for optimal results. A 6 or 7 Red Star Invisible Woman (MCU) is capable of handling the situation if the opposing Professor is at 5 Red Stars or less. Begin by using Black Cat’s Special ability to stun the enemy Franklin. Next, with your Franklin, utilize the Ultimate ability and target the enemy Professor. Follow up with IW’s Special ability directed at the enemy Professor, which should eliminate him. If successful, the rest of the battle should proceed smoothly. However, if the enemy Professor survives, luck will play a role, and your Professor must act before theirs to turn the tide in your favor."
    },
    "Fantastic Four (MCU) + Mephisto + Thanos (Endgame)": {
        "Quasar + Black Cat + Songbird + Ares + Apocalypse": "1 – Use Black Cat’s Special to Stun Franklin. Activate Songbird’s Ultimate for maximum impact. With Quasar, avoid hitting Thanos (Endgame) prematurely to prevent triggering his Passive ability when his HP drops below 50%. Instead, hit 3 enemies on the other side with his Ultimate. Finally, Apocalypse’s Ultimate, followed by Empowered Basic attacks, is used to finish off Thanos (Endgame) effectively.",
        "Mercs for Money + Knull + Sasquatch, or any other pre-Taunt (no Deathpool and Daken)": "2 – Sasquatch is there solely to endure Mephisto’s initial attack, as targeting OML or Pandapool could lead to everything falling apart. Use Pandapool’s Ultimate and target Franklin. Old Man Logan (OML) will assist, fill his Speed Bar, and play after him, and most importantly, before Franklin or IW (MCU). So use his Special, making sure to target Franklin again. Then, use Knull’s Special ability. Once OML plays his Ultimate, the fight should become manageable, allowing you to finish it successfully."
    },
    "Immortal Weapon": {
        "Vigilante": " (focus on Iron Fist)"
    },
    "Infestation": {
        "Insidious Six + Vulture + Green Goblin (Classic)": " – do not attack Big Time untill Green Goblin (Classic) turn and with him use Ultimate"
    },
    "Insidious Six + Vulture + Shocker": {
        "Hive-Mind + Knull (no Venom)": " – start with Knull’s Special on the weakest enemy, use Void Knight Ultimate on Superior Spider-Man",
        "Underworld + Kestrel (no Nobu)": " – focus on Vulture",
        "Mercs For Money": " – focus on Hobgoblin, Stun Superior Spider-Man with OML Special",
        "Cabal + Kang + Super Skrull": " – start with Skrull’s Basic",
        "Orchis": " – Nimrod’s Special on Superior Spider-Man",
        "Nightstalker": " – focus on Hobgoblin",
        "Thunderbolt": " – focus on Hobgoblin"
    },
    "Insidious Six + Vulture +Green Goblin (Classic)": {
        "Hive-Mind + Knull (no Venom)": " – start with Knull’s Special on the weakest enemy, use Void Knight Ultimate on Superior Spider-Man",
        "Mercs For Money": " – focus on Hobgoblin, Stun Superior Spider-Man with OML Special",
        "Nightstalker": " – focus on Hobgoblin"
    },
    "Liberty": {
        "Brimstone": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Mercs for Money + Nightcrawler + Dormammu (no Deathpool and Daken)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Fantastic Four (MCU) + Emma Frost (no The Thing)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Hive-Mind + Knull (no Venom)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Liberty": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Absolute A-Force + Odin/Mephisto (no Wasp)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Orchis + Odin/Mephisto (no Omega Sentinel)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Nightstalker + Odin/Mephisto (no Moon Knight)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Astral": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Annihilator + Phoenix Force (no Silver Surfer and Ultimus)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin)."
    },
    "Liberty + Professor X": {
        "Quasar + Apocalypse + Songbird + Jean Grey + Storm": "1 – To execute the counter effectively, use Ultimate with Songbird. Activate Storm’s Special, specifically targeting Falcon (Joaquin). Employ Jean’s Special, targeting Peggy. Deploy Quasar’s Special to impact three enemies simultaneously. Conclude by defeating Professor using Apocalypse’s Ultimate, followed by an Empowered Basic attack."
    },
    "New Mutant": {
        "Orchis": " (focus on Magik)",
        "Insidious SIx + Vulture + Green Goblin (Classic)": " (focus on Magik)",
        "Immortal Weapon": " (start with Sword Master’s Special)",
        "Hellfire Club": " (focus on Magik)"
    },
    "Nightstalkers + Mephisto": {
        "Undying": " – you do not even need Scarlet Witch (Zombie)"
    },
    "Odin + Black Knight + Cosmic Ghost Rider + Gorr + Emma Frost": {
        "Hive-Mind + Knull + Silver Sable (no Venom and Gvenom)": " – use Knull’s Special on his first turn",
        "Liberty + Mephisto (no War Machine)": " – use Mephisto Empowered Basic on Odin, then normal Basic on Odin",
        "Ares + Mephisto + Black Knight + Phoenix Force": " – use Mephisto Empowered Basic on Odin, then normal Basic on Odin"
    },
    "Phoenix Force + Mephisto + Ares": {
        "Quasar + Ares + Havok + Storm + Jean Grey": " (Stun Magneto (Phoenix Force) with Storm, Stun Mephisto with Havok, and Ability Block Omega Red (Phoenix Force) with Quasar’s Ultimate)",
        "Nightstalker + Quasar + Ares": " (focus on Mephisto, Stun Omega Red (Phoenix Force) with Agatha’s Special, after Mephisto is down focus on Omega)",
        "Absolute A-Force + Quasar + Shadow King": " (focus on Mephisto)",
        "Liberty + Odin": " (Stun Omega Red (Phoenix Force) with Peggy Charter, and focus on him)",
        "Phoenix Force + Mephisto + Scarlet Witch (Zombie) / Quasar": " focus on Mephisto",
        "Mercs for Money + Quasar": " (focus on Mephisto, Panda’s Ultimate + OML’s Special + Quasar’s Special; he needs to die after those 3 attacks. Huge punchups possible if you can kill Mephisto before any of the enemies play)"
    },
    "Phoenix Force + Gladiator + Thanos (Endgame)": {
        "Knull + Ares + Void Knight + Carnage + Gorr / Red Goblin": " (with Void Knight use Ultimate – target Magneto (Phoenix Force); with Knull use Special)",
        "Apocalypse + Red Hulk + Havok + Songbird + Super Skrull": " (start with Skrull’s Basic on Gladiator, use Red Hulk’s Special on Omega, and focus on Omega Red (Phoenix Force)"
    },
    "Professor Xavier + Black Knight + Dormammu + Shadow King + Emma Frost (X-Men)": {
        "Fantastic Four (MCU) + Black Cat + Ares": "1 – Black Cat should be a Skirmisher, while Franklin and Invisible Woman (MCU) should be Strikers. Use Black Cat’s Special ability and target Professor Xavier. Then, use the Special abilities of both Franklin and Invisible Woman (MCU), also targeting Professor Xavier. This should be enough to take him out. Once Professor Xavier is defeated, the rest of the fight becomes much easier."
    },
    "Professor Xavier + Knull + Nightcrawler + Shadow King + Emma Frost (X-Men)": {
        "Brimstone": " – if you have diamonds on Daimon Hellstrom, and if there is at least one non-GT20 character, this is a really easy fight"
    },
    "Underworld": {
        "Gamma": " (hard counter)",
        "Knowhere": " (hard counter)"
    },
    "Vigilante": {
        "Mighty Avengers": "1 – This is more than just a good counter. Don’t hold back any abilities—focus on Daredevil (Modern) right from the start because he has Taunt. With Falcon, use his Special ability first, then follow up with his Ultimate. It’s an easy fight for the Mighty Avengers.",
        "Vigilante": "2 – Your Silver Sable can reduce the duration of all positive effects on opponents, while their Silver Sable cannot. This is because Silver Sable’s ability to do so only works when used on offense and with a full Vigilante team. This allows you to remove most of the positive effects from your opponents, giving you an advantage. Focus on taking out Silver Sable and Hit Monkey first, followed by Daredevil (Modern) and Punisher. Save Elektra for last."
    },
    "X-Treme X-Men + Phoenix Force Duo": {
        "Hellfire Club": " (Stun Omega Red)"
    }
};
