const dicionario = {
    "Absolute A-Force": {
        "Absolute A-Force": "2 – One of the best counters for Absolute A-Force is Absolute A-Force. Your Kahhori passively, on Spawn, attacks the opponent Kahhori first, applies Exposed to her and prevents her from playing twice at the start. So the opponent Kahhori will only be able to use Special in her third turn. Focus on Ms. Marvel (Classic) until she loses Taunt. With Kahhori – twice Basic, then in her second turn – Special, with Ms. Marvel (Classic) – Ultimate. When the opponent Ms. Marvel (Classic) loses Taunt, switch your focus to the rest of the opponents. Kahhori’s and Medusa’s Ultimate can deal massive damage and eliminate most of the opposing team. After that, it’s all about bringing the fight to the end. Leave Ms. Marvel (Classic) for last.",
        "Gamma + Mephisto (no She-Hulk)": "3 – With Mephisto, play Empowered Basic on Ms. Marvel (Classic), and with Red Hulk use Special on her. You can use Special with Mephisto on his second turn. When Kahhori plays her Special, Red Hulk will get 5 Charged and will be able to use Ultimate, thus applying his Battlefield Effect to the opponent’s side. Opponents will have all negativities from Mephisto losing Empowered and Red Hulk Ultimate, but most importantly Heal Block, Trauma, and Bleed. After Mephisto plays his Ultimate – you’ll eliminate them without a problem. When Ms. Marvel (Classic) loses Taunt, focus on Kahhori. The Deathproofs you get from Mephisto’s Battlefield Effect and the Brawn’s Passive (as well as Deflects on Spawn) are essential for your team to withstand attacks. If Mephisto and Red Hulk are maxed, massive punch-ups are possible.",
        "Knowhere + Odin + Apocalypse (no Star-Lord (Annihilation) and Thor (Infinity War))": "4 – Nova is a fast enough character to play after Kahhori and allows Odin to Assist him. After that happens, with Odin, when it’s his turn to play, play Special (if you’re not Ability Block). When you apply the Battlefield Effect on the enemy side, everything will become much easier. Huge punch ups are possible if Odin is Maxed – Especially if he is GT20 (but it doesn’t need to be). Apocalypse is there to passively increase Odin’s Health and Accuracy. And if he manages to play, to use Ultimate and Empowered Basic on Ms. Marvel (Classic). If he doesn’t make it, if he is killed before his turn to play, the fight may be delayed, but you eventually win.",
        "Gamma + Apocalypse + Morgan Le Fay (no She-Hulk and Abomination)": "5 – If your Morgan Le Fay and Red Hulk are solidly upgraded (at least level 100 and GT19), you can destroy the opposing Absolute A-Force team with this combination. A solid punch-up is possible (assuming Apocalypse is maxed), but do not try more than 25%. Red Hulk should be Raider, MLF Skirmisher, and Apoc Striker. MLF should be positioned next to Red Hulk. With Red Hulk, play Special on Ms. Marvel (Classic) which will fill Apocalypsi’s Speed ​​Bar and enable him to play his Ultimate and Empowered Basic, thus eliminating Ms. Marvel (Classic). MLF will also get a Speed ​​Bar, so she will play before Kahhori and we use Ultimate with her, which will apply Ability Block to Kahhori. So Kahhori won’t be able to use Special and cause us huge problems. Soon after Red Hulk will build up enough Charged to use his Ultimate and when we do, victory is upon us. Eliminate Kahhori first, then Medusa.",
        "Cabal + Mephisto + Ares": "6 – Cabal, Mephisto, and Ares can get Absolute A-Force if it’s a weaker team than yours. Around 1.5 million punch downs is a good limit. With Mephisto, play Empowered Basic on Ms. Marvel (Classic), and focus on her from the start. When you eliminate her, focus on Kahhori."
    },
    "Absolute A-Force + Super Skrull": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – With Mephisto use Empowered Basic on Ms. Marvel (Classic). With Knull, Red Goblin and Void Knight use Ultimates. Those 3 attacks should be enough to put at least one of the opponents in red HP, and you will get enough Speed ​​Bar to continue destroying opponents. Focus on Ms. Marvel (Classic) and Kahhori.",
        "Absolute A-Force": "2 – We are forced to attack Ms. Marvel (Classic) at the start, so don’t save Abilities, use them all, and your primary target is Ms. Marvel (Classic) until she loses Taunt. When that happens, use Ultimate with Kahhori, but attack the other opponents (do not touch Ms. Marvel), then do the same with Medusa. It will certainly eliminate some of the opponents if your Kahhori and Medusa are strong enough. Focus on opponent Kahhori, then Medusa and Skrull, leave Ms. Marvel (Classic) for the end.",
        "Cabal + Mephisto + Ultimus": "3 – With Ultimus (he sould be Raider), use Special on the first turn, then Ultimate (you need to target Ms. Marvel (Classic) because she has Taunt). With Mephisto, Empowered Basic on Ms. Marvel (Classic). With Cabal characters, use all Abilities if you can (do not save anything). Focus on Ms. Marvel (Classic) first, then on Kahhori.",
        "Liberty": "4 – Use the Falcon (Joaquin) Special on the Skrull and with Peggy Stun Kahhori. Focus on Kahhori and Skrull, then Medusa."
    },
    "Absolute A-Force + Super Skrull + Dormammu": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – With Mephisto use Empowered Basic on Ms. Marvel (Classic). With Knull, Red Goblin and Void Knight use Ultimates. Those 3 attacks should be enough to put at least one of the opponents in red HP, and you will get enough Speed ​​Bar to continue destroying opponents. Focus on Ms. Marvel (Classic) and Kahhori. Mephisto will stop Revives.",
        "Liberty": "2 – Use the Falcon (Joaquin) Special on the Skrull and with Peggy Stun Kahhori. Focus on Kahhori and Skrull, then Medusa.",
        "Cabal + Mephisto + Ultimus": "3 – With Ultimus (he should be Raider), use Special on the first turn, then Ultimate (you need to target Ms. Marvel (Classic) because she has Taunt). With Mephisto, Empowered Basic on Ms. Marvel (Classic). With Cabal characters, use all Abilities if you can (do not save anything). Focus on Ms. Marvel (Classic) first, then on Kahhori. Mephisto will prevent Revives.",
        "Absolute A-Force": "4 – We are forced to attack Ms. Marvel (Classic) at the start, so don’t save Abilities, use them all, and your primary target is Ms. Marvel (Classic) until she loses Taunt. When that happens, use Ultimate with Kahhori, but attack the other opponents (do not touch Ms. Marvel), then do the same with Medusa. It will certainly eliminate some of the opponents if your Kahhori and Medusa are strong enough. Focus on opponent Kahhori, then Medusa and Skrull, leave Ms. Marvel (Classic) for the end. Medusa can permanently kill opponents with her attacks, and it will neutralize Dormammu’s Revive. Also, any opponent you apply Exposed on with Kahhori will not be able to Revive."
    },
    "Absolute A-Force + Odin": {
        "Hive-Mind + Knull + Mephisto (no Venom and Gwenom)": "1 – Mephisto – Empowered Basic on Ms. Marvel (Classic), and on his second turn Basic on the same target. With Void Knight use Ultimate, with Knull – also Ultimate. With Carnage Special, and with Red Goblin Ultimate. Even before we do all these attacks, we will lower at least one of the opponents to red HP, so we will get a bunch of Speed ​​Bar and play constantly until we eliminate them all."
    },
    "Absolute A-Force + Mephisto + Super Skrull": {
        "Liberty + Knull": "2 – With Falcon (Joaquin) use the Special on the Skrull. With Peggy Carter – Special on Kahhori. With Knull – Special on Kahhori. With Captain (Sam) use Ultimate, and with Patriot – Special. After Kahhori, focus on Mephisto then Skrull then Medusa. Leave Ms. Marvel (Classic) for the end."
    },
    "Absolute A-Force + Odin + Super Skrull": {
        "Liberty + Mephisto (no War Machine)": "1 – Use Mephisto’s Empowered Basic on Odin, then hit him with a Basic attack. Target Skrull with Falcon’s (Joaquin) Special.",
        "Mephisto + Ares + Ultimus + Apocalypse + Scarlet Witch (Zombie)": "2 – Use Mephisto’s Empowered Basic on Ms. Marvel (Classic), then finish her with Ultimus Ultimate. After the kill, Ultimus through his Passive, fills Speed Bar by 15% to all his allies, and your Apocalypse will play before enemy Odin. Kill Odin with Apocalypse Ultimate + Empowered Basic.",
        "Liberty": "3– Use Facon’s (Joaquin) Special targeting Super Skrull, then full focus on Odin, but do not have him as the primary target when using Peggy’s Special (Odin should be one of the adjacent targets).",
        "Cabal + Apocalypse + Ultimus": "4 – With Ultimus, play Basic on his first and second turns targeting Ms. Marvel (Classic). On his third turn, go for the kill – use the Ultimate. After that, focus on Odin."
    },
    "Kahhori + Ms. Marvel (Classic) + Medusa/Super Skrull + Mephisto + Thanos (Endgame)": {
        "Liberty + Knull (no War Machine)": "1 – With Falcon (Joaquin) we use Special on Skrull, and if there is Medusa instead of Skrull, then on Kahhori. With Peggy Special on Kahhori, with Cap (Sam) use Ultimate, and with Patriot Special. Focus on the opponent’s side opposite from where Ms. Marvel (Classic) stands. Try not to hit her. With Knull, use the Special on the first turn. Mephisto must be eliminated before he can use his Ultimate. Don’t be afraid to drop Thanos (Endgame) below 50% HP. Leave Ms. Marvel (Classic) for the end."
    },
    "Kahhori + Ms. Marvel (Classic) + Spider-Man (Pavitr) + Red Goblin + Carnage": {
        "Mighty Avengers": "1 – Use Hercules’ Special on Ms. Marvel (Classic) to remove all her buffs and, most importantly, all her Charges. After that, focus your attacks on Kahhori until your Invisible Woman gets a turn. When she does, use her Ultimate on Ms. Marvel (Classic) to Stun her, allowing you to defeat her without worrying about her countering and gaining more Charges. Once Ms. Marvel (Classic) is eliminated, the battle is essentially won. Your next main target should be Kahhori, and that’s it.",
        "Undying + Mephisto": "2 – Use Mephisto’s Empowered Basic and standard Basic attacks on Ms. Marvel (Classic). If she survives, continue to focus on her until she is defeated. Once she is down, shift your attention to Kahhori for an easy victory."
    },
    "Kahhori + Ms. Marvel (Classic) + Odin + Knull + Dormammu": {
        "Liberty + Mephisto (no War Machine)": "1 – Start by using Maphisto’s Basic attack on Odin, followed by Mephisto’s Special attack on Odin. Then, Falcon (Joaquin), uses his Special target the enemy character next to Odin. Next, Peggy should use her special attack on Kahhori. Use Cap (Sam)’s Ultimate, and have Patriot use his Special. Save Ms. Marvel (Classic) for the end."
    },
    "Alpha Flight": {
        "Mercs For Money": "1 – Hard Counter – With OML use Special on the first turn and Ultimate on the second turn. With other characters, use all available Abilities.",
        "Liberty": "2 – Hard Counter – use all available Abilities. Use Special with Joaquin on Northstar, and with Peggy, use Special on Wolverine.",
        "Illuminati": "3 – Focus on Sasquatch until it loses Taunt, then switch your focus to Northstar and Guardian. Use all available Abilities. Stun Wolverine with Captain Britain."
    },
    "Annihilator + Odin + Professor Xavier": {
        "Quasar + Ares + Mephisto + Phoenix Force (Quasar needs to have his Awakened Ultimate)": "1 – With Quasar, use his Ultimate but be careful not to hit Odin; instead, try to hit Professor X. Professor doesn’t need to be the primary target, but Odin should not be hit by Quasar Ultimate at all. When Odin uses his Special, he won’t be able to apply the Battlefield Effect because Quasar will have already applied his. With Mephisto, use the Empowered Basic attack on Odin. For Phoenix, make sure to use her Special, and for Ares, also use his Special, targeting Professor X. Once you eliminate Professor X, your primary target will be Odin unless he is defeated before you eliminate Professor. Be cautious not to take Thanos (Endgame) below 50% before Phoenix dies and can use her Dark Phoenix Special. Alternatively, you can defeat Thanos with Quasar’s Special. Avoid using Ultimates until Professor X is defeated. When Dark Phoenix drops Thanos’s (Endgame) health below 50% with her Special, it won’t trigger his Passive."
    },
    "3 New Annihilator + Odin + Ares": {
        "3 New Absolute A-Force + Apocalypse + Red Hulk": "1 – With Kahhori, use the Basic on Gladiator to remove his Taunt, then use the Basic on Ares to remove his Immunity. Use Medusa’s Special and Ms. Marvel’s (Classic) Ultimate to attack Odin. With Kahhori, use the Special, and with Red Hulk, also use the Special – but target a different character since you cannot rewind Odin’s Speed Bar. With Apocalypse, use the Ultimate, followed by the Empowered Basic on Thanos (Endgame) to avoid taking passive damage from him.",
        "Liberty": "2 – With Falcon (Joaquin), use Special on Gorr to reduce his Speed Bar. This will allow Odin to act before all the other opponents. Odin will use his Special, but won’t apply the Battlefield Effect since he hasn’t had a chance to assist before his first move. With Peggy, use her Special on Ares, and then focus on Odin as your primary target. All other characters should also concentrate on Odin. Use Captain Sam’s Ultimate, Patriot’s Special, and War Machine’s Special to deal damage. If your three new Liberty characters are GT20 (specifically if their Overpower rating is higher than the opponent’s), you should have enough damage to eliminate Odin before his turn. If you don’t have an advantage in Overpower, this counter-strategy is not recommended (but still can work). Once Odin is eliminated, the rest of the battle will become much easier.",
        "Liberty + Mephisto (no War Machine)": "3 – With Mephisto: Empowered Basic and Basic on Odin, with Falcon (Joaquin): Special on Gorr, with Peggy: Special on enemy next to Odin. After Patriot Special and Captain Sam Ultimate Odin should be eliminated. After that finish the rest. Focus on Gorr first, and try to leave Thanos (Endgame) for the end.",
        "Nightstalker + Mephisto (no Moon Knight)": "4 – This counter works best if your Blade and Oath have a higher Overpower ranking compared to the opponent’s Gladiator and Odin. Start by using Mephisto’s Empowered Basic attack along with his standard Basic attack on Gladiator. With Blade, use his Ultimate ability on Ares (especially if Ares is positioned next to Gladiator – that’s an ideal scenario). Once you’ve taken down the two opposing protectors, shift your full focus to Odin. If you have the Overpower advantage, you should be able to defeat him before he gets a chance to act. However, we don’t recommend using this counter if you lack the Overpower advantage mentioned above.",
        "Orchis + Mephisto (no Omega Sentinel": "5 – This is an ideal counter to use if your Orchis characters have a higher Overpower rating compared to the opponent’s Odin and Gladiator. Start by using Mephisto’s Empowered Basic followed by a Basic on Gladiator. With Scientist Supreme, activate her Ultimate. Use Nimrod’s Special ability to target all enemies, and then use Lady Deathstrike’s Special or Basic ability to attack the remaining opponent with Taunt (either Gladiator or Ares). When using Sentinel, activate his Ultimate on Odin and have his minions focus their attacks on Odin as well. This should be enough to eliminate Odin. Afterward, concentrate on defeating the remaining opponents. However, we do not recommend using this counter strategy if your Orchis team does not have an Overpower advantage over Gladiator and Odin."
    },
    "Annihilator + Knull": {
        "Hive-Mind + Knull (no Venom)": "1 – Start with Void Knight’s Ultimate, then use Carnage’s Special. You need to target the Gladiator because he has the Taunt. With Knull, use his Special first, as it will summon an extra Carnage and give you a significant Speed Bar boost when you bring any opponent’s health down to the red zone. Knull’s next move should be his Ultimate ability. By this point, some enemies should be defeated, and others should have low health. Be cautious of Thanos (Endgame) and his passive damage, as it can create a challenging situation. However, as long as at least one Carnage, Knull, and one other character are still alive, you should be able to win this easily. If your Hive-Mind characters are weak, consider swapping out Gwen for Odin. With Odin on your team, victory becomes much simpler.",
        "Mercs For Money + Ares (no Deathpool)": "2 – Ares is mainly there for his passive abilities. After Ultimus and Gorr take their turns, Ares will most likely be defeated. The key point for you is to ensure that Old Man Logan (OML) gets his turn. Ares will strip all buffs from the enemy team, allowing you to Stun Thanos (Endgame) with OML right at the start of the battle. Focus on taking down Knull as your priority. Use Pandapool’s Ultimate and Daken’s Special, combined with OML’s assist and the damage from his Special, to eliminate Knull quickly. With Deadpool you can Stun Gladiator and after that focus on Gorr and Thanos (Endgame). When Thanos (Endgame) deals passive damage, it’s crucial that both Daken and Old Man Logan have Revive available to sustain the fight.",
        "Super Skrull + Odin + Doctor Doom + Phoenix Force Duo": "3 – This is an easy fight for this team. Start with Skrull by using his Special, followed by his Basic attack. For Odin, use his Special. When Gladiator loses Taunt, shift your focus to Knull. While Phoenix Force and Doom aren’t crucial, it’s still helpful to have them on your team (though Doom might end up dying from friendly fire). Make sure to include one additional Hero and two Villain characters alongside Skrull and Odin."
    },
    "Gorr + Gladiator + Thanos (Endgame) + Odin + Moondragon": {
        "Liberty + Mephisto (no War Machine)": "1 – With Mephisto – Empowered Basic + standard Basic on Odin. With Falcon (Joaquin) – Special on character next to Odin. Odin should be dead, if not – finish him off. After he dies, feel free to drop Thanos (Endgame) below 50% HP to trigger his Passive, and then finish off the opponents.",
        "Absolute A-Force": "2 – With Kahhori use Basic on Gladiator, then Basic on Odin, then Special on Odin. After that focus on Odin: Medusa Special, Ms. Marvel (Classic) Ultimate, and Ironheart Special on target next to Odin if he has really low HP, or Basic directly on Odin if he has a bit more HP – he should be down. With Wasp, you can Stun Gladiator (Special). After that trigger Thanos (Endgame) Passive, and finish the enemies.",
        "Nightstalker + Mephisto (no Moon Knight": "3 – With Mephisto use Empowered Basic and Basic on Gladiator. With Blade use Ultimate on Gladiator. If your Mephisto and Blade are huge (especially if Blade is GT20 and opponent Gladiator is not GT20), he should be dead. Then switch your focus to Odin. With Oath using Ultimate on Odin, and with assistance from Blade it can kill him if he is GT19 and Blade + Oath are GT20 (and they should be because they are great for Xavier Saga). After Odin is down, finish the rest. So, basically, this counter can work without problems if your Blade and Oath are GT20 and opponent Odin and Gladiator are not."
    },
    "Astral": {
        "Undying + Phoenix Force Duo (without Scarlet Witch (Zombie))": "1 – With Iron Man (Zombie), use Special on Emma Frost (X-Men), and with Hela Ultimate on Emma Frost (X-Men). You will spread every negativity from her to the rest of the Astral team – most importantly Ability Block. With Omega Red (Phoenix Force), use a Special on the far left or far right opponent. With Juggernaut (Zombie), use the Ultimate to hit three opponents standing next to each other."
    },
    "Astral + Cosmic Ghost Rider": {
        "Vigilante": "1 – With Silver Sable, use Ultimate. That will put Ability Block on Strange and Emma (X-Men), so with Hit Monkey, we can use Ultimate on Ancient One to Stun her. With Daredevil (Modern), we use Special on Strange, and with Punisher Ultimate on Shadow King (if Punisher does not have Ability Block). Eliminate Strange first, then Shadow King and the rest of the opponents.",
        "Absolute A-Force": "2 – Don’t save anything of Abilities. Focus on Doctor Strange first, then Shadow King. Cosmic Ghost Rider will die from AOE damage. Finish Emma and Ancient at the end.",
        "Mercs for Money + Apocalypse": "3 – Use Panda’s Ultimate and target Shadow King. With OML, use the Special to target Strange. You might not succeed in Stunning him, but that’s okay. With Apocalypse, use both the Ultimate and Empowered Basic abilities to target Shadow King. With assistance from OML, Shadow King should be eliminated. Then, focus on Strange using OML’s Ultimate and Daken’s Special. Once Strange is defeated, finish off the remaining enemies.",
        "Liberty": "4 – Focus on Strange from the beginning. Do not hesitate to use any Abilities. Once Strange is eliminated, switch your focus to Shadow King. If you have some of the Liberty characters at Overpower Rank 11 (at least Peggy) and the opposing Astral team does not, then this will be a very easy fight for you."
    },
    "Brimstone": {
        "Brimstone + Emma Frost (no Elsa Bloodstone)": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Winter Guard": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Fantastic Four (MCU) + Emma Frost": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Emma Frost + Emma Frost (X-Men) + Storm + Jean Grey + Ares": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective.",
        "Emma Frost + Black Cat + Scarlet Witch (Zombie) + Havok + Songbird": " When facing a standard Brimstone team, it’s important to include Emma Frost to reduce their Speed by 10%. You’ll also want a character who can prevent their Speed from increasing, such as Franklin, Zombie Scarlet Witch, or Emma Frost (X-Men). Additionally, it’s helpful to have a fast character who can control the enemy team, like Black Cat, Havok, or Storm. Ares can also be very useful, as he can remove Taunt from Living Mummy, allowing you to control the Daimon Hellstrom right from the start. Black Cat is especially valuable because she can remove Revive Once from Living Mummy—so if you bring her, you won’t need Ares for that purpose. This means you don’t need to use Mythic characters like Professor X, Odin, or Mephisto when facing a full Brimstone team. However, be aware that Quasar is a bad choice against Brimstone, as he prevents any Speed stat manipulation, making Emma Frost’s passive ability ineffective."
    },
    "Exalted X-Men": {
        "Insidious Six + Vulture + Green Goblin (Classic)": " Avoid hitting Angel whenever you can",
        "Secret Warrior": " Avoid hitting Angel whenever you can",
        "Nick Fury + Odin + 3 (you can use Blastaar and Thunderstrike and one more)": " Start with Fury’s Special and Odin’s Basic",
        "Illuminati + Sentry (no Mr. Fantastic)": " Focus on Angel",
        "Starjammer": " Avoid hitting Angel whenever you can"
    },
    "Fantastic Four (MCU) + Professor Xavier + Nightcrawler": {
        "Quasar + Mephisto + Ares + Storm + Black Cat": "1 – With Black Cat use Special on Franklin Richards, with Storm use Special on Invisible Woman (MCU), with Quasar use Ultimate on Professor Xavier."
    },
    "Fantastic Four (MCU) + Professor Xavier + Odin": {
        "Quasar + Ares + Black Cat + Songbird + Havok or Mephisto if punch up is huge": "1 – Use Songbird’s Ultimate, use Black Cat’s Special to stun Franklin. With Quasar, use the Ultimate ability and aim at Professor Xavier. Once Xavier and Franklin are eliminated, shift your focus to Odin."
    },
    "Fantastic Four (MCU) + Mephisto + Thanos (Endgame)": {
        "Quasar + Black Cat + Songbird + Ares + Apocalypse": "1 – Use Black Cat’s Special to Stun Franklin. Activate Songbird’s Ultimate for maximum impact. With Quasar, avoid hitting Thanos (Endgame) prematurely to prevent triggering his Passive ability when his HP drops below 50%. Instead, hit 3 enemies on the other side with his Ultimate. Finally, Apocalypse’s Ultimate, followed by Empowered Basic attacks, is used to finish off Thanos (Endgame) effectively."
    },
    "Insidious Six + Vulture + Shocker": {
        "Hive-Mind + Knull (no Venom)": " – start with Knull’s Special on the weakest enemy, use Void Knight Ultimate on Superior Spider-Man",
        "Underworld + Kestrel (no Nobu)": " – focus on Vulture",
        "Mercs For Money": " – focus on Hobgoblin, Stun Superior Spider-Man with OML Special",
        "Cabal + Kang + Super Skrull": " – start with Skrull’s Basic",
        "Orchis": " – Nimrod’s Special on Superior Spider-Man",
        "Nightstalker": " – focus on Hobgoblin"
    },
    "Insidious Six + Vulture +Green Goblin (Classic)": {
        "Hive-Mind + Knull (no Venom)": " – start with Knull’s Special on the weakest enemy, use Void Knight Ultimate on Superior Spider-Man",
        "Mercs For Money": " – focus on Hobgoblin, Stun Superior Spider-Man with OML Special"
    },
    "Liberty": {
        "Brimstone": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Mercs for Money + Nightcrawler + Dormammu (no Deathpool and Daken)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Fantastic Four (MCU) + Emma Frost (no The Thing)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Hive-Mind + Knull (no Venom)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Liberty": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Absolute A-Force + Odin/Mephisto (no Wasp)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Orchis + Odin/Mephisto (no Omega Sentinel)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Nightstalker + Odin/Mephisto (no Moon Knight)": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin).",
        "Astral": " Because of the Passive damage that Peggy can do and the certain damage that you will definitely receive from the Falcon (Joaquin) at the beginning of the battle, take into account the Overpower level of the Liberty team. If they have a higher Overpower level than your characters, the fight can become unpredictable. In all of these fights (whichever counter team you use) focus on Peggy Carter first. Once you eliminate her, your next target should be Falcon (Joaquin)."
    },
    "New Mutant": {
        "Orchis": " (focus on Magik)",
        "Insidious SIx + Vulture + Green Goblin (Classic)": " (focus on Magik)",
        "Immortal Weapon": " (start with Sword Master’s Special)"
    },
    "Odin + Black Knight + Cosmic Ghost Rider + Gorr + Emma Frost": {
        "Hive-Mind + Knull + Silver Sable (no Venom and Gvenom)": " – use Knull’s Special on his first turn",
        "Liberty + Mephisto (no War Machine)": " – use Mephisto Empowered Basic on Odin, then normal Basic on Odin"
    },
    "Phoenix Force + Mephisto + Ares": {
        "Quasar + Ares + Havok + Storm + Jean Grey": " (Stun Magneto (Phoenix Force) with Storm, Stun Mephisto with Havok, and Ability Block Omega Red (Phoenix Force) with Quasar’s Ultimate)",
        "Nightstalker + Quasar + Ares": " (focus on Mephisto, Stun Omega Red (Phoenix Force) with Agatha’s Special, after Mephisto is down focus on Omega)",
        "Absolute A-Force + Quasar + Shadow King": " (focus on Mephisto)",
        "Liberty + Odin": " (Stun Omega Red (Phoenix Force) with Peggy Charter, and focus on him)",
        "Phoenix Force + Mephisto + Scarlet Witch (Zombie) / Quasar": " focus on Mephisto"
    },
    "Phoenix Force + Gladiator + Thanos (Endgame)": {
        "Knull + Ares + Void Knight + Carnage + Gorr / Red Goblin": " (with Void Knight use Ultimate – target Magneto (Phoenix Force); with Knull use Special)"
    },
    "Shadow Conclave": {
        "Daimon Hellstrom + Living Mummy + Strange (Heartless) + Guardian + Iron Patriot": " If opposing Thanos is strong enough to reduce your Living Mummy’s health to 25% or lower with his Special, you will lose the battle. Your Daimon needs to be huge.",
        "Professor Xavier + Quasar + Kingpin + Storm + Havok": " Stun Executioner with Storm, Stun High Evolutionary with Havok",
        "Fantastic Four (MCU) + Professor Xavier + Odin (no The Thing and Human Torch)": " focus on High Evolutionary",
        "Odin + Knull + Quasar + Blastaar + Thunderstrike": " Use Special with Odin on his first turn.",
        "Fantastic Four (MCU) + Professor Xavier (no The Thing)": " focus on High Evolutionary",
        "Brimstone": " If opposing Thanos is strong enough to reduce your Living Mummy’s health to 25% or lower with his Special, you will lose the battle. Your Daimon needs to be huge."
    },
    "Underworld": {
        "Gamma": " (hard counter)"
    },
    "Vigilante": {
        "Mighty Avengers": "1 – This is more than just a good counter. Don’t hold back any abilities—focus on Daredevil (Modern) right from the start because he has Taunt. With Falcon, use his Special ability first, then follow up with his Ultimate. It’s an easy fight for the Mighty Avengers."
    },
    "X-Treme X-Men + Phoenix Force Duo": {
        "Hellfire Club": " (Stun Omega Red)"
    }
};
